import React from "react";
import { DISPLAY_CONTENTS } from "./shared-styles";

export const NS_MUTED = { color: "#8A8AA0" } as const;
export const NS_DIM = { color: "#4A4A6A" } as const;
export const NS_TEXT = { color: "#C0C0D0" } as const;
export const NS_ACCENT_GREEN = { color: "#4ACA6A" } as const;
export const NS_INPUT_STYLE = { color: "#C0C0D0", border: "1px solid #1A1A2A", background: "#0A0A12" } as const;
export const NS_BORDER_B = { borderBottom: "1px solid #1A1A2A" } as const;
export const NS_DARK = { color: "#2A2A4A" } as const;
export const NS_SUBDIM = { color: "#3A3A5A" } as const;
export const NS_BRIGHT = { color: "#D0D0E0" } as const;
export const NS_SOFT = { color: "#B0B0C0" } as const;
export const NS_MID = { color: "#5A5A7A" } as const;
export const NS_GOLD = { color: "#CAAA3A" } as const;
export const NS_BLUE = { color: "#5A9ACA" } as const;
export const NS_RED = { color: "#FF5A5A" } as const;
export const NS_WARN = { color: "#FF6A6A" } as const;
export const NS_PALE = { color: "#9A9AB0" } as const;
export const NS_FAINT = { color: "#6A6A8A" } as const;
export const NS_MID2 = { color: "#7A7A9A" } as const;
export const NS_BG_DARK = { background: "#0A0A12" } as const;
export const NS_BG_DARKER = { background: "#080810" } as const;
export const NS_BORDER_DARK = { border: "1px solid #1A1A2A" } as const;
export const NS_BTN_CONFIRM = { color: "#4ACA6A", background: "#0A1A10", border: "1px solid #1A3A20" } as const;
export const NS_BTN_CANCEL = { color: "#CA4A4A", background: "#1A0A0A", border: "1px solid #3A1A1A" } as const;
export const NS_BADGE = { color: "#4A4A6A", background: "#0A0A12", border: "1px solid #12121E" } as const;
export const NS_BTN_EDIT = { background: "#0A0A14", border: "1px solid #1A1A2A", color: "#5A5A7A" } as const;
export const NS_BTN_DELETE = { background: "#1A0808", border: "1px solid #2A1212", color: "#8A3A3A" } as const;
export const NS_BTN_REP_MINUS = { background: "#1A0A0A", border: "1px solid #2A1A1A", color: "#AA4A4A" } as const;
export const NS_BTN_REP_PLUS = { background: "#0A1A0A", border: "1px solid #1A2A1A", color: "#4AAA4A" } as const;
export const NS_DETAIL_INPUT = { color: "#B0B0C0", border: "1px solid #12121E", background: "#080810" } as const;
export const NS_ROLE_INPUT = { color: "#8A8AA0", border: "1px solid #1A1A2A", background: "#0A0A12" } as const;
export { DISPLAY_CONTENTS as NS_DISPLAY_CONTENTS };
export const NS_BTN_LOAD = { color: "#5A9ACA", background: "#080A14", border: "1px solid #101A2A" } as const;
export const NS_NAME_INPUT = { color: "#D0D0E0", border: "1px solid #12121E", background: "#080810" } as const;
export const NS_STAT_BTN = { color: "#5A5A7A", border: "1px solid #12121E", background: "#080810" } as const;
export const NS_STAT_VALUE = { color: "#7A7A9A", background: "#0A0A14", border: "1px solid #151520" } as const;
export const NS_BORDER_SECTION = { borderBottom: "1px solid #151520" } as const;
export const NS_BORDER_SUBSECTION = { borderBottom: "1px solid #12121E" } as const;
export const NS_BAR_BG = { background: "#0A0A12", border: "1px solid #10101A" } as const;
export const NS_DETAIL_SELECT = { color: "#8A8AA0", border: "1px solid #12121E", background: "#080810" } as const;
export const NS_TYPE_SELECT = { color: "#5A5A7A", background: "#0A0A12", border: "1px solid #12121E" } as const;
export const NS_TEXTAREA = { color: "#A0A0B8", border: "1px solid #12121E", background: "#080810", minHeight: 50 } as const;
export const NS_REP_BAR_BG = { background: "#0A0A12", border: "1px solid #151520" } as const;
export const NS_ICON_BLUE_SOFT = { color: "#5A9ACA", opacity: 0.7 } as const;
export const NS_ICON_GOLD_DIM = { color: "#CAAA3A", opacity: 0.6 } as const;
export const NS_ICON_GOLD_SOFT = { color: "#CAAA3A", opacity: 0.7 } as const;
export const NS_ICON_GOLD_HALF = { color: "#CAAA3A", opacity: 0.5 } as const;
export const NS_ICON_BLUE_DIM = { color: "#5A9ACA", opacity: 0.6 } as const;
export const NS_ICON_GREEN_SOFT = { color: "#4ACA6A", opacity: 0.7 } as const;
export const NS_ICON_RED_SOFT = { color: "#FF5A5A", opacity: 0.7 } as const;
export const NS_EMPTY_ICON = { color: "#1A1A2A", margin: "0 auto 6px" } as const;
export const NS_EMPTY_ICON_LG = { color: "#1A1A2A", margin: "0 auto 8px" } as const;
export const NS_SAVE_PRESET_BG = { color: "#C0C0D0", border: "1px solid #1A2A1A", background: "#0A0A12" } as const;
export const NS_LOAD_PRESET_BG = { color: "#5A9ACA", background: "#0A0A14", border: "1px solid #101A2A" } as const;
export const NS_ADD_GOLD = { color: "#CAAA3A", background: "#14120A", border: "1px solid #2A2A1A" } as const;
export const NS_SECTION_BORDER = { borderBottom: "1px solid #12121E" } as const;
export const NS_PANEL_BG = { background: "#0A0A14", border: "1px solid #1A1A2A" } as const;
export const NS_ICON_AMBER_SOFT = { color: "#CA8A4A", opacity: 0.7 } as const;
export const NS_ICON_MINT_SOFT = { color: "#6ACA8A", opacity: 0.7 } as const;
export const NS_OVERLAY_BG = { background: "#000000E6" } as const;
export const NS_DIVIDER_DARK = { background: "#1A1A2A" } as const;
export const NS_BORDER_THIN = { border: "1px solid #1A1A2A" } as const;
export const NS_GRAY_BADGE = { color: "#6A6A8A", background: "#6A6A8A08", border: "1px solid #6A6A8A10" } as const;
export const NS_GRAY_BADGE_LG = { color: "#6A6A8A", background: "#6A6A8A10", border: "1px solid #6A6A8A20" } as const;
export const NS_DELETE_BTN_ALT = { color: "#AA4A4A", background: "#1A0808", border: "1px solid #2A1212" } as const;
export const NS_NO_EVENTS = { pointerEvents: "none" as const } as const;
export const NS_BORDER_TOP_DARK = { borderTop: "1px solid #1A1A2A" } as const;
export const NS_DIM_SIZE_LABEL = { background: "#000A", color: "#5A5A7A" } as const;
export const NS_STAT_TEAL_BOX = { background: "#3ACABA08", border: "1px solid #3ACABA12" } as const;
export const NS_STAT_BLUE_BOX = { background: "#6A9ADA08", border: "1px solid #6A9ADA12" } as const;
export const NS_STAT_AMBER_BOX = { background: "#CA8A4A08", border: "1px solid #CA8A4A12" } as const;
export const NS_GOLD_SUBTLE_BOX = { background: "#CAAA3A08", border: "1px solid #CAAA3A15" } as const;
export const NS_BLUE_SUBTLE_BOX = { background: "#5A9ACA06", border: "1px solid #5A9ACA10" } as const;
export const NS_BORDER_TOP_PANEL = { borderTop: "1px solid #12121E" } as const;
export const NS_INPUT_DIM = { color: "#5A5A7A", background: "#0A0A14", border: "1px solid #151520" } as const;
export const NS_INPUT_DARK = { color: "#5A5A7A", background: "#060609", border: "1px solid #12121E" } as const;
export const NS_GRAY_SELECT = { color: "#6A6A8A", background: "#0A0A12", border: "1px solid #1A1A2A" } as const;
export const NS_PLACEHOLDER_ICON = { color: "#1A1A2A", margin: "0 auto" } as const;
export const NS_MIN_W_100 = { minWidth: 100 } as const;
export const NS_TOOLBAR_BG = { background: "linear-gradient(180deg, #0C0C14 0%, #080810 100%)", borderBottom: "1px solid #1A1A2A", boxShadow: "0 1px 4px rgba(0,0,0,0.4)" } as const;
export const NS_BADGE_DARK = { color: "#FF6A6A", background: "#1A0A0A", border: "1px solid #2A1212" } as const;
export const NS_RED_DARK = { color: "#6A3A3A" } as const;
export const NS_GREEN = { color: "#5ACA7A" } as const;
export const NS_TEAL = { color: "#3ACABA" } as const;
export const NS_STEEL = { color: "#6A9ADA" } as const;
export const NS_AMBER = { color: "#CA8A4A" } as const;
export const NS_BROWN = { color: "#6A4A2A" } as const;
export const NS_SKY = { color: "#8AAACA" } as const;
export const NS_SLATE = { color: "#3A5A7A" } as const;
export const NS_MUTED2 = { color: "#8A8AAA" } as const;

export const nsToggleStyle = (on: boolean, c: string, cfg: { onBgA?: string; onBdrA?: string; offC?: string; offBg?: string; offBdr?: string } = {}) => ({
  color: on ? c : (cfg.offC || "#5A5A7A"),
  background: on ? `${c}${cfg.onBgA || "12"}` : (cfg.offBg || "transparent"),
  border: `1px solid ${on ? `${c}${cfg.onBdrA || "30"}` : (cfg.offBdr || "#12121E")}`,
});
export const nsEditToggle = (on: boolean, a: string) => nsToggleStyle(on, a, { onBgA: "15", onBdrA: "30", offBg: "#0A0A14", offBdr: "#1A1A2A" });
export const nsIconToggle = (on: boolean, a: string) => nsToggleStyle(on, a, { onBgA: "20", onBdrA: "60", offBg: "#0A0A14", offBdr: "#151520" });
export const nsTypeToggle = (on: boolean, c: string, off = "#4A4A6A") => nsToggleStyle(on, c, { onBgA: "12", onBdrA: "30", offC: off });
export const nsToggleBtn = (on: boolean, c: string, offC = "#5A5A7A") => nsToggleStyle(on, c, { onBgA: "08", onBdrA: "15", offC, offBdr: "#1A1A2A" });

export const nsAccentBtn = (a: string) => ({ color: a, background: `${a}08`, border: `1px solid ${a}15` });
export const nsAccentDim = (a: string) => ({ color: a, opacity: 0.6 });
export const nsAccentHalf = (a: string) => ({ color: a, opacity: 0.5 });
export const nsAccentSoft = (a: string) => ({ color: a, opacity: 0.7 });
export const nsAccentBg = (a: string) => ({ background: `${a}08`, border: `1px solid ${a}15` });
export const nsBgColor = (c: string) => ({ background: c });
export const nsColorInput = (c: string) => ({ color: c, border: "1px solid #12121E", background: "#080810" });
export const nsGradLine = (a: string) => ({ background: `linear-gradient(90deg, ${a}15, transparent)` });
export const nsPriBadge = (c: string) => ({ color: c, background: `${c}10`, border: `1px solid ${c}20` });
export const nsIconTint = (c: string, o = 0.6) => ({ color: c, opacity: o });
export const nsColorBox = (c: string) => ({ background: `${c}12`, border: `1px solid ${c}20` });
export const nsSliderThumb = (c: string, pct: number) => ({ left: `calc(${pct}% - 4px)`, background: "#FFF", boxShadow: `0 0 6px ${c}` });
export const nsSliderAccent = (c: string) => ({ accentColor: c, background: "#12121E" });
export const nsChevronCollapse = (a: string, collapsed: boolean) => ({ color: a, opacity: 0.5, transform: collapsed ? "rotate(-90deg)" : "rotate(0)", transition: "transform 0.2s" });
export const nsSubtleBox = (c: string) => ({ background: `${c}08`, border: `1px solid ${c}12` });
export const nsTierBadge = (c: string) => ({ color: c, background: `${c}10`, border: `1px solid ${c}18` });
export const nsMetaBadge = (c: string) => ({ color: c, background: `${c}10`, border: `1px solid ${c}15` });
export const nsDragFade = (d: boolean, o = 0.35) => ({ opacity: d ? o : 1, transition: "opacity 0.2s" });
export const nsCatBorder = (c: boolean) => ({ borderBottom: c ? "none" : "1px solid #12121E" });
export const nsRarityDot = (r: string) => ({ background: r === "uncommon" ? "#5ACA7A" : "#4A4A6A" });
export const nsIncomeColor = (v: number) => ({ color: v >= 0 ? "#CAAA3A" : "#FF5A5A" });
export const nsRevColor = (v: number) => ({ color: v > 0 ? "#4ACA6A" : "#3A3A5A" });
export const nsExpColor = (v: number) => ({ color: v > 0 ? "#FF5A5A" : "#3A3A5A" });
export const nsNetColor = (v: number) => ({ color: v >= 0 ? "#CAAA3A" : "#FF5A5A" });
export const nsTextColor = (c: string) => ({ color: c });
export const NS_PRIORITY_BADGE = (c: string) => ({ color: `${c}80`, background: `${c}08`, border: `1px solid ${c}10` });
export const nsHasText = (has: boolean) => ({ color: has ? "#8A8AA0" : "#2A2A4A" });
export const nsAccentBorder = (a: string, o = "15") => ({ border: `1px solid ${a}${o}` });
export const nsTabActive = (on: boolean, a: string) => ({ color: on ? a : "#5A5A7A", fontWeight: on ? 600 : 400, background: on ? `${a}06` : "transparent", borderBottom: on ? `2px solid ${a}` : "2px solid transparent", marginBottom: -1 });
export const nsHpBar = (pct: number) => ({ width: `${pct}%`, background: pct > 50 ? "#4ACA6A" : pct > 25 ? "#CAAA3A" : "#FF4A4A" });
export const nsWoundBar = (pct: number) => ({ width: `${pct}%`, background: "#FF4A4A" });
export const nsPinToggle = (on: boolean) => ({ color: on ? "#CAAA3A" : "#4A4A6A", background: on ? "#CAAA3A12" : "#0A0A12", border: `1px solid ${on ? "#CAAA3A30" : "#12121E"}` });
export const nsAccentTile = (a: string, dm: boolean) => ({ background: `${a}08`, border: `1px solid ${a}12`, cursor: dm ? "pointer" : "default" });
export const nsFooterInput = (a: string) => ({ background: "#0A0A14", border: `1px solid ${a}30`, color: "#C0C0D0" });
export const nsGradientDiv = (a: string) => ({ background: `linear-gradient(90deg, transparent, ${a}10, transparent)` });
export const nsInnerPad16 = (ip: React.CSSProperties) => ({ ...ip, padding: "16px" });
export const nsInnerPad14_16 = (ip: React.CSSProperties) => ({ ...ip, padding: "14px 16px" });
export const NS_PANEL_GREEN = (ip: React.CSSProperties) => ({ ...ip, border: "1px solid #1A3A20" });
export const NS_PANEL_BLUE = (ip: React.CSSProperties) => ({ ...ip, border: "1px solid #101A2A" });
export const nsDropTarget = (ps: React.CSSProperties, over: boolean, a: string) => ({ ...ps, border: over ? `1px solid ${a}40` : ps.border, transition: "border-color 0.2s" });
export const nsAccentIcon = (a: string) => ({ background: `linear-gradient(135deg, ${a}15, ${a}05)`, border: `1px solid ${a}25`, boxShadow: `0 0 20px ${a}08, inset 0 1px 0 rgba(255,255,255,0.03)` });
export const nsNameInput = (a: string) => ({ color: a, fontFamily: "'Trebuchet MS', 'Tahoma', sans-serif", border: `1px solid ${a}40`, background: "#0A0A14", width: "100%", maxWidth: 500 });
export const nsIncomeIcon = (v: number) => ({ ...nsIncomeColor(v), opacity: 0.7 });
export const nsBadgeCustom = (c: string) => ({ color: c || "#FF6A6A", background: "#1A0A0A", border: "1px solid #2A1212" });
export const nsNameTitle = (a: string, tsFn: (v: string) => React.CSSProperties) => ({ ...tsFn(a), fontFamily: "'Trebuchet MS', 'Tahoma', sans-serif", textShadow: `0 0 30px ${a}15` });
export const nsPortraitImg = (offX: number, offY: number, scale: number) => ({ position: "absolute" as const, top: "50%", left: "50%", transform: `translate(calc(-50% + ${offX}px), calc(-50% + ${offY}px)) scale(${scale / 100})`, transformOrigin: "center center", minWidth: "100%", minHeight: "100%", objectFit: "cover" as const, pointerEvents: "none" as const });
export const nsPhotoDrag = (dragging: boolean) => ({ width: "100%", height: "100%", overflow: "hidden" as const, cursor: dragging ? "grabbing" : "grab", position: "relative" as const, userSelect: "none" as const });
export const nsPortraitFrame = (a: string) => ({ border: `1px solid ${a}20`, borderRadius: 5, overflow: "hidden" as const, position: "relative" as const });
export const NS_PORTRAIT_VIEW = (w: number, h: number) => ({ width: w, height: h, borderRadius: 5, overflow: "hidden" as const, border: "1px solid #1A1A2A", position: "relative" as const });
export const nsRepBar = (pct: string, c: string) => ({ width: pct, background: "linear-gradient(90deg, #FF2A2A, #CC6A4A, #6A7A9A, #5ACA7A, #FFD700)", boxShadow: `0 0 8px ${c}40` });
export const NS_ENTITY_REP_BAR = (pct: string) => ({ width: pct, background: "linear-gradient(90deg, #FF1A1A, #CC6A4A, #6A7A9A, #4ABA6A, #FFD700)", opacity: 0.8 });